.github/pull_request_template.md
Improve PR handling of checkboxes
=> DEVX-2155: Address checkbox behavior with comments

cp-all-in-one-cloud/docker-compose.connect.local.yml, cp-all-in-one-cloud/docker-compose.yml, cp-all-in-one-community/docker-compose.yml, cp-all-in-one/docker-compose.yml
Updates monitoring interceptors and kafka-connect datagen usage to 6.0.1
https://confluentinc.atlassian.net/browse/DEVX-2294
TODO: Validate behaviors
=> DEVX-2294: Updates monitoring interceptors and datagen usage to 6.0.1

utils/ccloud-generate-cp-configs.sh
https://confluentinc.atlassian.net/browse/DEVX-2338
Update code
=> DEVX-2447: ccloud-generate-cp-configs.sh has diverged in cp-all-in-one

cp-all-in-one-security/README.md
https://confluentinc.atlassian.net/browse/DEVX-2439
cp-all-in-one-security --> pointer to cp-demo
=> DEVX-2439: Create a cp-all-in-one-security and link to cp-demo

cp-all-in-one-cloud/docker-compose.connect.distributed.yml, cp-all-in-one-cloud/docker-compose.yml, cp-all-in-one-community/docker-compose.yml, cp-all-in-one-kraft/docker-compose.yml, cp-all-in-one/docker-compose.yml
https://confluentinc.atlassian.net/browse/DEVX-2625
=> DEVX-2625: updated datagen version from 0.4.0-6.1.0 to 0.5.0-6.2.0

cp-all-in-one-cloud/docker-compose.connect.distributed.yml, cp-all-in-one-cloud/docker-compose.yml, cp-all-in-one-community/docker-compose.yml, cp-all-in-one-kraft/docker-compose.yml, cp-all-in-one/docker-compose.yml
=> Update datagen version to 6.2.1

cp-all-in-one-cloud/docker-compose.connect.distributed.yml, cp-all-in-one-cloud/docker-compose.yml, cp-all-in-one-community/docker-compose.yml, cp-all-in-one-kraft/docker-compose.yml, cp-all-in-one/docker-compose.yml
https://confluentinc.atlassian.net/browse/DEVX-2703
Address https://cwiki.apache.org/confluence/display/KAFKA/KIP-208%3A+Add+SSL+support+to+Kafka+Connect+REST+interface
=> DEVX-2703: update connect configurations for KIP-208

cp-all-in-one-cloud/docker-compose.yml, cp-all-in-one-community/docker-compose.yml, cp-all-in-one-kraft/docker-compose.yml, cp-all-in-one/docker-compose.yml
Update datagen Docker image to latest versions of connect & datagen
=> Update datagen to 0.5.3-7.1.0

cp-all-in-one-cloud/docker-compose.yml, cp-all-in-one-cloud/myprops.properties, cp-all-in-one-cloud/update_run.sh
Temporary workaround for https://confluentinc.atlassian.net/browse/MMA-11806
To allow Confluent Control Center to connect to Confluent Cloud
=> MMA-11806 workaround

Dockerfile, action.yml, entrypoint.sh
=> Add required fields for new GitHub Action

cp-all-in-one-community/docker-compose.yml, cp-all-in-one-kraft/docker-compose.yml
- Details in #101 
- Also cleans up community to remove interceptors (not needed without C3)
Sister PR to https://github.com/confluentinc/examples/pull/1117
=> Add ksqlDB and C3 into KRaft docker compose

cp-all-in-one-cloud/docker-compose.yml, cp-all-in-one-community/docker-compose.yml, cp-all-in-one-kraft/docker-compose.yml, cp-all-in-one/docker-compose.yml
manually tested with cp-quickstart
=> upgrade datagen images to datagen 0.6.0 / CP 7.3.0

cp-all-in-one-kraft/docker-compose.yml
Simplify docker-compose by specifying cluster_id
=> Cherry pick PR 117 to 7.4.0-post

cp-all-in-one-kraft/docker-compose.yml
- change KRaft example to use cp-server image instead of cp-kafka
- add metrics reporting to broker and controller
[asana](https://app.asana.com/0/1201906632362444/1204907421528575/f)
=> fix C3 config in KRaft example

cp-all-in-one-cloud/docker-compose.yml, cp-all-in-one-community/docker-compose.yml, cp-all-in-one-kraft/docker-compose.yml, cp-all-in-one/docker-compose.yml
=> update datagen connect images to 0.6.2-7.5.0

cp-all-in-one-kraft/docker-compose.yml
[asana](https://app.asana.com/0/1201906632362444/1204907421528575/f)
=> fix: enable broker metrics in C3 in kraft example

cp-all-in-one-security/oauth/README.md
Documentation to enable CLI SSO in the README file.
=> README changes for enabling CLI SSO

cp-all-in-one-security/oauth/helper/functions.sh
Add rolebindings for Everyone group from Okta dev IdP to access demo cluster resources
=> Rolebindings for everyone group

cp-all-in-one-security/oauth/README.md, cp-all-in-one-security/oauth/docker-compose.yml, cp-all-in-one-security/oauth/helper/cp_config.sh, cp-all-in-one-security/oauth/helper/functions.sh, cp-all-in-one-security/oauth/helper/idp_config.sh, cp-all-in-one-security/oauth/metrics/prometheus.yml, cp-all-in-one-security/oauth/start.sh, cp-all-in-one-security/oauth/templates/realm-export.json
https://confluentinc.atlassian.net/browse/CPSEC-395
Adds support for KSQL OAuth
Validated cp-all-in-one-security
=> CPSEC-395: Docker example for KSQL OAuth

cp-all-in-one-security/oauth/docker-compose.yml, cp-all-in-one-security/oauth/mount/client.properties, cp-all-in-one-security/oauth/mount/superuser.properties, cp-all-in-one-security/oauth/templates/client.template, cp-all-in-one-security/oauth/templates/superuser.template
This PR contains the following two changes:
- FQDN changes made as a part of https://confluentinc.atlassian.net/browse/CPSEC-881. (Removed the deprecated `secured` urls & replaced with new ones)
- Incorporated changes to allow IDP endpoints, done as a part of https://confluentinc.atlassian.net/browse/CPSEC-863 where supporting changes have been done in ce-kafka. 
Tested by bringing up the containers of SR, KSQL, and others & verified the logs. Tested via producing messages to Kafka - directly as well as via SchemaRegistry. 
=> [CPSEC-863][CPSEC-881] cp-all-in-one-security : FQDN changes and IDP Endpoints Whitelisting

README.md
This reverts commit ced76cf21734f869aee22756fdf96944b0cc0e65.
=> Revert "Add Confluent Cloud promotional banner to README"
